---
owner: "NetaMx"
repo: "upptime"

sites:
  - name: "NetaMx Site"
    url: "https://neta.mx/"
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
  - name: "API Gateway"
    url: "https://xkxzvljbtd.execute-api.us-east-2.amazonaws.com"
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
      - 403
  - name: "Api ops Prods"
    url: "https://api-ops-prod.neta.mx:3013"
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
      - 403
      - 503
      - 502

assignees:
  - "adrianhorizon"

status-website:
  cname: "status.ops.neta.mx"
  logoUrl: "https://raw.githubusercontent.com/NetaMx/upptime/master/assets/Logo_Neta_Close.png"
  favicon: "https://raw.githubusercontent.com/NetaMx/upptime/master/assets/Logo_Neta_Close.png"
  name: ""
  introTitle: "**NetaMx** *Insurance, the new way!* - Uptime monitor and status page, powered entirely by [Upptime](https://upptime.js.org/) and [GitHub Pages](https://pages.github.com/)."
  introMessage: "This is the **NetaMx** status page which uses **real-time** data from our [GitHub repository](https://github.com/NetaMx/upptime)."
  theme: "light"
  navbar:
    - title: "Status"
      href: "/"
    - title: "GitHub"
      href: "https://github.com/$OWNER/$REPO"
    - title: "About Us"
      href: "https://neta.mx/"
  metaTags:
    - name: "color-scheme"
      content: "light"
    - name: "robots"
      content: "noindex"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

user-agent: "adrianhorizon"