---
owner: "NetaMx"
repo: "upptime"

sites:
  - name: "NetaMx Site"
    url: $SECRET_SITE_NETA
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
  - name: "Mi Tienda"
    url: $SECRET_SITE_MITIENDA
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
      - 403
  - name: "Data Analitycs"
    url: $SECRET_SITE_REDASH
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
  - name: "Autenticacion"
    url: $SECRET_SITE_OPS_SECURITY
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
   - name: "Facturacion"
    url: $SECRET_SITE_OPS_INVOICE
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
   - name: "Reportes"
    url: $SECRET_SITE_OPS_PDFGERATOR
    maxResponseTime: 2000
    expectedStatusCodes:
      - 404
    - name: "Entregas"
    url: $SECRET_SITE_OPS_DELIVERY
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
    - name: "Ordenes"
    url: $SECRET_SITE_OPS_ORDER
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
    - name: "Ordenes V2"
    url: $SECRET_SITE_RENGOKU
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200
    - name: "Gestion de Tiendas"
    url: $SECRET_SITE_OPS_STORE
    maxResponseTime: 2000
    expectedStatusCodes:
      - 200   

assignees:
  - "adrianhorizon"
  - "yisusvii"

status-website:
  cname: "status.ops.neta.mx"
  logoUrl: "https://raw.githubusercontent.com/NetaMx/upptime/master/assets/Logo_Neta_Close.png"
  favicon: "https://raw.githubusercontent.com/NetaMx/upptime/master/assets/Logo_Neta_Close.png"
  name: ""
  introTitle: "**NetaMx** Estado de Servicios"
  introMessage: "Esta es la pagina de estado de servicios en tiempo real para **NetaMx** "
  theme: "light"
  navbar:
    - title: "Status"
      href: "/"
  metaTags:
    - name: "color-scheme"
      content: "light"
    - name: "robots"
      content: "noindex"

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

user-agent: "adrianhorizon"
